project:
  type: website
  # post-render:
  #   - "cp -rnv static/. _site" # source: https://github.com/quarto-dev/quarto-cli/discussions/4162#discussioncomment-4831352
  output-dir: _site
  resources:
    - assets/**/*

website:
  title: "Nadhir Vincent Hass"
  site-url: "https://nadhirvincent.com"
  site-path: "/"
  description: "Data Scientist and Machine Learning Engineer with expertise in ML, AI, Computer Vision, and Cloud Computing."
  favicon: assets/nadhir/img/logo_rounded.svg
  page-navigation: true
  back-to-top-navigation: true
  twitter-card:
    creator: "@nadhirvincent"
    site: "@nadhirvincent"
    card-style: summary_large_image
  comments:
    utterances:
      repo: vincehass/nadhir
      label: utterances
      theme: body-light
      issue-term: title
  # search:
  #   algolia:
  #     index-name: nadhirvincent_com_pages
  #     application-id: APPID
  #     search-only-api-key: APIKEY
  #     show-logo: false
  # index-fields:
  #   href: url
  #   title: title
  #   section: subtitle
  #   text: body

  navbar:
    logo: assets/nadhir/img/logo_rounded.svg
    # logo: assets/nadhir/img/logo_noBg.svg
    logo-href: /
    tools:
      - icon: github
        href: https://www.github.com/vincehass
    right:
      - text: About
        aria-label: "About Me"
        href: /about/index.html
      - text: Blog
        aria-label: "Blog Posts"
        href: /blog/index.html
      - text: Talks
        aria-label: "Invited Talks"
        href: /talk/index.html
      - text: Publications
        aria-label: "Publications"
        href: /publication/index.html
      - text: Projects
        aria-label: "Project Portfolio"
        href: /project/index.html

  page-footer:
    left: >-
      &#169; 2024 Nadhir Vincent Hass &#8729; Made with [Quarto](https://quarto.org)
    center: |
      <a class="link-dark me-1" href="/accessibility.html" title="Accessibility commitment" target="_blank" rel="noopener">{{< fa universal-access >}}</a>
      <a class="link-dark me-1" href="https://linkedin.com/in/nadhir-vincent-hass-216391aa" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
      <a class="link-dark me-1" href="https://github.com/vincehass" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
      <a class="link-dark me-1" href="https://orcid.org/0000-0000-0000-0000" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
      <a class="link-dark me-1" href="https://scholar.google.com/citations?user=RVK0V44AAAAJ&hl=en" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
      <a class="link-dark me-1" href="mailto:nadhir@example.com" title="Email" target="_blank" rel="noopener">{{< fa envelope >}}</a>

    right:
      - text: "Accessibility"
        aria-label: "Accessibility Commitment"
        href: /accessibility.html
      - text: "Contact"
        aria-label: "Contact Form"
        href: "/contact.html"
      - text: "License"
        aria-label: "License Details"
        href: /license.html
      - icon: rss
        href: /blog/index.xml

format:
  html:
    theme:
      light:
        - cosmo
        - assets/nadhir-theme-light.scss
        - assets/nadhir/colors-light.scss
        - assets/nadhir/fonts.scss
      dark:
        - cosmo
        - assets/nadhir-theme-dark.scss
        - assets/nadhir/colors-dark.scss
    highlight-style:
      light: assets/nadhir/a11y-light.theme
      dark: assets/nadhir/a11y-dark.theme
    code-link: true
    pagetitle: "{{< meta title >}}"
    lightbox: true

execute:
  freeze: auto

include-in-header: assets/nadhir/umami.html
